exports.ENCRYP_CONFIG = {
  SECRET_ENCRPPWD_KEY: process.env.SECRET_ENCRPPWD_KEY,
  SECRET_ENCRPPWD_IV: process.env.SECRET_ENCRPPWD_IV,
  SECRET_ENCRPMERGEDPWD_KEY: process.env.SECRET_ENCRPMERGEDPWD_KEY,
  SECRET_ENCRPMERGEDPWD_IV: process.env.SECRET_ENCRPMERGEDPWD_IV,
  ENCRYPTION_ALGO: process.env.ENCRYPTION_ALGO,
  SPLIT_SYMBOL: process.env.SPLIT_SYMBOL,
}
